### Gene Search

In [7]:
from pynoma import GeneSearch
gs = GeneSearch(3, "idua")
df, df_clin = gs.get_data()
df

,Variant ID,Gene,Consequence,Annotation,Flags,Allele Count,Allele Number,Allele Frequency,Number of Homozygotes,Source,Chromosome,Location,Reference,Alternative
0,4-987010-C-G,IDUA,c.-75C>G,5_prime_UTR_variant,[],1,149172,0.000007,0,Genome,4,987010,C,G
1,4-987013-G-A,IDUA,c.-72G>A,5_prime_UTR_variant,[],3,151256,0.000020,0,Genome,4,987013,G,A
2,4-987014-C-T,IDUA,c.-71C>T,5_prime_UTR_variant,[],37,152092,0.000243,0,Genome,4,987014,C,T
3,4-987021-T-C,IDUA,c.-64T>C,5_prime_UTR_variant,[],2,146758,0.000014,0,Genome,4,987021,T,C
4,4-987023-C-G,IDUA,c.-62C>G,5_prime_UTR_variant,[],1,152126,0.000007,0,Genome,4,987023,C,G
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1199,4-1004450-G-A,IDUA,c.*57G>A,3_prime_UTR_variant,[],1,152196,0.000007,0,Genome,4,1004450,G,A
1200,4-1004450-G-GCA,IDUA,c.*59_*60dup,3_prime_UTR_variant,[],1,152196,0.000007,0,Genome,4,1004450,G,GCA
1201,4-1004452-A-C,IDUA,c.*59A>C,3_prime_UTR_variant,[],7,152152,0.000046,0,Genome,4,1004452,A,C
1202,4-1004458-C-G,IDUA,c.*65C>G,3_prime_UTR_variant,[],2,152180,0.000013,0,Genome,4,1004458,C,G
1203,4-1004459-C-G,IDUA,c.*66C>G,3_prime_UTR_variant,[],23,152202,0.000151,0,Genome,4,1004459,C,G

In [8]:
df_clin

,clinical_significance,clinvar_variation_id,gold_stars,major_consequence,pos,variant_id
0,Uncertain significance,350186,1,5_prime_UTR_variant,987014,4-987014-C-T
1,Uncertain significance,990330,0,5_prime_UTR_variant,987083,4-987083-C-T
2,Pathogenic,550458,1,start_lost,987085,4-987085-A-C
3,Pathogenic,639529,1,start_lost,987086,4-987086-T-C
4,Likely pathogenic,557150,1,start_lost,987087,4-987087-G-A
...,...,...,...,...,...,...
404,Uncertain significance,558359,1,stop_gained,1004349,4-1004349-G-T
405,Likely benign,743489,1,synonymous_variant,1004381,4-1004381-G-T
406,Likely benign,754394,1,synonymous_variant,1004390,4-1004390-A-T
407,Pathogenic,960079,1,stop_lost,1004391,4-1004391-T-C
408,Pathogenic,11920,0,stop_lost,1004391,4-1004391-T-G

In [11]:
df, df_clin = gs.get_data(standard=False)
df

,consequence,flags,gene_id,gene_symbol,hgvs,hgvsc,hgvsp,lof,lof_filter,lof_flags,pos,rsid,transcript_id,variant_id,exome,genome,lof_curation
0,5_prime_UTR_variant,[],ENSG00000127415,IDUA,c.-75C>G,c.-75C>G,None,None,None,None,987010,None,ENST00000247933,4-987010-C-G,None,"{'ac': 1, 'ac_hemi': 0, 'ac_hom': 0, 'an': 149...",None
1,5_prime_UTR_variant,[],ENSG00000127415,IDUA,c.-72G>A,c.-72G>A,None,None,None,None,987013,None,ENST00000247933,4-987013-G-A,None,"{'ac': 3, 'ac_hemi': 0, 'ac_hom': 0, 'an': 151...",None
2,5_prime_UTR_variant,[],ENSG00000127415,IDUA,c.-71C>T,c.-71C>T,None,None,None,None,987014,rs886059748,ENST00000247933,4-987014-C-T,None,"{'ac': 37, 'ac_hemi': 0, 'ac_hom': 0, 'an': 15...",None
3,5_prime_UTR_variant,[],ENSG00000127415,IDUA,c.-64T>C,c.-64T>C,None,None,None,None,987021,rs1473070711,ENST00000247933,4-987021-T-C,None,"{'ac': 2, 'ac_hemi': 0, 'ac_hom': 0, 'an': 146...",None
4,5_prime_UTR_variant,[],ENSG00000127415,IDUA,c.-62C>G,c.-62C>G,None,None,None,None,987023,rs1447064463,ENST00000247933,4-987023-C-G,None,"{'ac': 1, 'ac_hemi': 0, 'ac_hom': 0, 'an': 152...",None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1199,3_prime_UTR_variant,[],ENSG00000127415,IDUA,c.*57G>A,c.*57G>A,None,None,None,None,1004450,None,ENST00000514224,4-1004450-G-A,None,"{'ac': 1, 'ac_hemi': 0, 'ac_hom': 0, 'an': 152...",None
1200,3_prime_UTR_variant,[],ENSG00000127415,IDUA,c.*59_*60dup,c.*59_*60dup,None,None,None,None,1004450,rs1393615274,ENST00000514224,4-1004450-G-GCA,None,"{'ac': 1, 'ac_hemi': 0, 'ac_hom': 0, 'an': 152...",None
1201,3_prime_UTR_variant,[],ENSG00000127415,IDUA,c.*59A>C,c.*59A>C,None,None,None,None,1004452,rs733349,ENST00000514224,4-1004452-A-C,None,"{'ac': 7, 'ac_hemi': 0, 'ac_hom': 0, 'an': 152...",None
1202,3_prime_UTR_variant,[],ENSG00000127415,IDUA,c.*65C>G,c.*65C>G,None,None,None,None,1004458,rs942204021,ENST00000514224,4-1004458-C-G,None,"{'ac': 2, 'ac_hemi': 0, 'ac_hom': 0, 'an': 152...",None
1203,3_prime_UTR_variant,[],ENSG00000127415,IDUA,c.*66C>G,c.*66C>G,None,None,None,None,1004459,rs529309396,ENST00000514224,4-1004459-C-G,None,"{'ac': 23, 'ac_hemi': 0, 'ac_hom': 0, 'an': 15...",None

In [12]:
df_clin

,clinical_significance,clinvar_variation_id,gold_stars,major_consequence,pos,variant_id
0,Uncertain significance,350186,1,5_prime_UTR_variant,987014,4-987014-C-T
1,Uncertain significance,990330,0,5_prime_UTR_variant,987083,4-987083-C-T
2,Pathogenic,550458,1,start_lost,987085,4-987085-A-C
3,Pathogenic,639529,1,start_lost,987086,4-987086-T-C
4,Likely pathogenic,557150,1,start_lost,987087,4-987087-G-A
...,...,...,...,...,...,...
404,Uncertain significance,558359,1,stop_gained,1004349,4-1004349-G-T
405,Likely benign,743489,1,synonymous_variant,1004381,4-1004381-G-T
406,Likely benign,754394,1,synonymous_variant,1004390,4-1004390-A-T
407,Pathogenic,960079,1,stop_lost,1004391,4-1004391-T-C
408,Pathogenic,11920,0,stop_lost,1004391,4-1004391-T-G

In [2]:
gs = GeneSearch(2, "idua")
df, _ = gs.get_data(standard=False, additional_population_info=True)
df

,consequence,flags,gene_id,gene_symbol,hgvs,hgvsc,hgvsp,lof,lof_filter,lof_flags,...,genome,lof_curation,African,Latino,Ashkenazi Jewish,East Asian,European (Finnish),European (non-Finnish),Other,South Asian
0,5_prime_UTR_variant,[],ENSG00000127415,IDUA,c.-72G>A,c.-72G>A,None,None,None,None,...,"{'ac': 2, 'ac_hemi': 0, 'ac_hom': 0, 'an': 311...",None,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.304291e-04,0.000000e+00,0.000000e+00
1,5_prime_UTR_variant,[],ENSG00000127415,IDUA,c.-71C>T,c.-71C>T,None,None,None,None,...,"{'ac': 10, 'ac_hemi': 0, 'ac_hom': 0, 'an': 31...",None,1.154468e-04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.207655e-04,9.191176e-04,0.000000e+00
2,5_prime_UTR_variant,[],ENSG00000127415,IDUA,c.-62C>G,c.-62C>G,None,None,None,None,...,"{'ac': 1, 'ac_hemi': 0, 'ac_hom': 0, 'an': 312...",None,1.155001e-04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
3,5_prime_UTR_variant,[],ENSG00000127415,IDUA,c.-55G>A,c.-55G>A,None,None,None,None,...,"{'ac': 1, 'ac_hemi': 0, 'ac_hom': 0, 'an': 312...",None,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.497726e-05,0.000000e+00,0.000000e+00
4,5_prime_UTR_variant,[],ENSG00000127415,IDUA,c.-51C>A,c.-51C>A,None,None,None,None,...,None,None,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1764,3_prime_UTR_variant,[],ENSG00000127415,IDUA,c.*53G>A,c.*53G>A,None,None,None,None,...,"{'ac': 1, 'ac_hemi': 0, 'ac_hom': 0, 'an': 313...",None,0.000000e+00,1.179245e-03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1765,3_prime_UTR_variant,[],ENSG00000127415,IDUA,c.*55C>T,c.*55C>T,None,None,None,None,...,"{'ac': 1, 'ac_hemi': 0, 'ac_hom': 0, 'an': 313...",None,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.482562e-05,0.000000e+00,0.000000e+00
1766,3_prime_UTR_variant,[],ENSG00000127415,IDUA,c.*59A>C,c.*59A>C,None,None,None,None,...,"{'ac': 1, 'ac_hemi': 0, 'ac_hom': 0, 'an': 313...",None,1.148897e-04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1767,3_prime_UTR_variant,[],ENSG00000127415,IDUA,c.*65C>G,c.*65C>G,None,None,None,None,...,"{'ac': 1, 'ac_hemi': 0, 'ac_hom': 0, 'an': 313...",None,0.000000e+00,0.000000e+00,0.000000e+00,6.418485e-04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1768,3_prime_UTR_variant,[],ENSG00000127415,IDUA,c.*66C>G,c.*66C>G,None,None,None,None,...,"{'ac': 3, 'ac_hemi': 0, 'ac_hom': 0, 'an': 313...",None,3.447483e-04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00

### Region Search

In [9]:
from pynoma import RegionSearch
rs = RegionSearch(3, 4, 1002741, 1002771)
df, _ = rs.get_data()
df

,Variant ID,Gene,Consequence,Annotation,Flags,Allele Count,Allele Number,Allele Frequency,Number of Homozygotes,Source,Chromosome,Location,Reference,Alternative
0,4-1002747-G-A,IDUA,p.Trp402Ter,stop_gained,[],130,151238,0.000860,0,Genome,4,1002747,G,A
1,4-1002750-C-T,IDUA,p.Ala403Val,missense_variant,[],2,150266,0.000013,0,Genome,4,1002750,C,T
2,4-1002751-C-G,IDUA,p.Ala403Ala,synonymous_variant,[],2,151840,0.000013,0,Genome,4,1002751,C,G
3,4-1002756-T-G,IDUA,p.Val405Gly,missense_variant,[],1,150082,0.000007,0,Genome,4,1002756,T,G
4,4-1002759-C-G,IDUA,p.Ser406Trp,missense_variant,[],3,151328,0.000020,0,Genome,4,1002759,C,G
5,4-1002766-C-T,IDUA,p.Ala408Ala,synonymous_variant,[],3,151864,0.000020,0,Genome,4,1002766,C,T
6,4-1002767-G-C,IDUA,p.Gly409Arg,missense_variant,[],2757,150922,0.018268,68,Genome,4,1002767,G,C
7,4-1002768-G-A,IDUA,p.Gly409Glu,missense_variant,[],2,151856,0.000013,0,Genome,4,1002768,G,A
8,4-1002770-AC-A,IDUA,p.Val411SerfsTer29,frameshift_variant,[],1,148668,0.000007,0,Genome,4,1002770,AC,A
9,4-1002770-A-C,IDUA,p.Thr410Pro,missense_variant,[],5,148666,0.000034,0,Genome,4,1002770,A,C

In [10]:
df, _ = rs.get_data(additional_population_info=True)
df

,Variant ID,Gene,Consequence,Annotation,Flags,Allele Count,Allele Number,Allele Frequency,Number of Homozygotes,Source,...,African,Amish,Latino,Ashkenazi Jewish,East Asian,European (Finnish),European (non-Finnish),Other,South Asian,Middle Eastern
0,4-1002747-G-A,IDUA,p.Trp402Ter,stop_gained,[],130,151238,0.000860,0,Genome,...,3.168877e-04,0.000000e+00,1.971868e-04,0.000000e+00,0.000000e+00,2.865877e-04,1.621128e-03,4.803074e-04,0.000000e+00,0.000000e+00
1,4-1002750-C-T,IDUA,p.Ala403Val,missense_variant,[],2,150266,0.000013,0,Genome,...,4.895721e-05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2,4-1002751-C-G,IDUA,p.Ala403Ala,synonymous_variant,[],2,151840,0.000013,0,Genome,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.944988e-05,0.000000e+00,0.000000e+00,0.000000e+00
3,4-1002756-T-G,IDUA,p.Val405Gly,missense_variant,[],1,150082,0.000007,0,Genome,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.482756e-05,0.000000e+00,0.000000e+00,0.000000e+00
4,4-1002759-C-G,IDUA,p.Ser406Trp,missense_variant,[],3,151328,0.000020,0,Genome,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.425693e-05,0.000000e+00,0.000000e+00,0.000000e+00
5,4-1002766-C-T,IDUA,p.Ala408Ala,synonymous_variant,[],3,151864,0.000020,0,Genome,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.418783e-05,0.000000e+00,0.000000e+00,0.000000e+00
6,4-1002767-G-C,IDUA,p.Gly409Arg,missense_variant,[],2757,150922,0.018268,68,Genome,...,5.894567e-02,0.000000e+00,1.057680e-02,9.243212e-03,1.628089e-02,0.000000e+00,4.872431e-04,1.294343e-02,1.048218e-03,9.740260e-03
7,4-1002768-G-A,IDUA,p.Gly409Glu,missense_variant,[],2,151856,0.000013,0,Genome,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.945768e-05,0.000000e+00,0.000000e+00,0.000000e+00
8,4-1002770-AC-A,IDUA,p.Val411SerfsTer29,frameshift_variant,[],1,148668,0.000007,0,Genome,...,2.484596e-05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
9,4-1002770-A-C,IDUA,p.Thr410Pro,missense_variant,[],5,148666,0.000034,0,Genome,...,1.242298e-04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00

In [11]:
df.iloc[:, 5:]

,Allele Count,Allele Number,Allele Frequency,Number of Homozygotes,Source,Chromosome,Location,Reference,Alternative,African,Amish,Latino,Ashkenazi Jewish,East Asian,European (Finnish),European (non-Finnish),Other,South Asian,Middle Eastern
0,130,151238,0.000860,0,Genome,4,1002747,G,A,3.168877e-04,0.000000e+00,1.971868e-04,0.000000e+00,0.000000e+00,2.865877e-04,1.621128e-03,4.803074e-04,0.000000e+00,0.000000e+00
1,2,150266,0.000013,0,Genome,4,1002750,C,T,4.895721e-05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2,2,151840,0.000013,0,Genome,4,1002751,C,G,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.944988e-05,0.000000e+00,0.000000e+00,0.000000e+00
3,1,150082,0.000007,0,Genome,4,1002756,T,G,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.482756e-05,0.000000e+00,0.000000e+00,0.000000e+00
4,3,151328,0.000020,0,Genome,4,1002759,C,G,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.425693e-05,0.000000e+00,0.000000e+00,0.000000e+00
5,3,151864,0.000020,0,Genome,4,1002766,C,T,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.418783e-05,0.000000e+00,0.000000e+00,0.000000e+00
6,2757,150922,0.018268,68,Genome,4,1002767,G,C,5.894567e-02,0.000000e+00,1.057680e-02,9.243212e-03,1.628089e-02,0.000000e+00,4.872431e-04,1.294343e-02,1.048218e-03,9.740260e-03
7,2,151856,0.000013,0,Genome,4,1002768,G,A,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.945768e-05,0.000000e+00,0.000000e+00,0.000000e+00
8,1,148668,0.000007,0,Genome,4,1002770,AC,A,2.484596e-05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
9,5,148666,0.000034,0,Genome,4,1002770,A,C,1.242298e-04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00

In [12]:
from pynoma import RegionSearch
rs = RegionSearch(2, 'X', 1002741, 1002771)
df, _ = rs.get_data(additional_population_info=True)
df

,Variant ID,Gene,Consequence,Annotation,Flags,Allele Count,Allele Number,Allele Frequency,Number of Homozygotes,Number of Hemizygotes,...,Reference,Alternative,African,Latino,Ashkenazi Jewish,East Asian,European (Finnish),European (non-Finnish),Other,South Asian
0,X-1002741-C-T,None,None,None,[par],1,31378,0.000032,0,0,...,C,T,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.488451e-05,0.000000e+00,0.000000e+00
1,X-1002742-G-A,None,None,None,[par],2,31316,0.000064,0,0,...,G,A,2.303086e-04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2,X-1002746-TATCA-T,None,None,None,[par],1,31376,0.000032,0,0,...,TATCA,T,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.489293e-05,0.000000e+00,0.000000e+00
3,X-1002765-TTATC-T,None,None,None,[par],9,31374,0.000287,0,0,...,TTATC,T,9.189065e-04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.486767e-05,0.000000e+00,0.000000e+00
4,X-1002767-ATCTATCTT-A,None,None,None,[par],1,31348,0.000032,0,0,...,ATCTATCTT,A,1.150483e-04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
5,X-1002771-ATCTT-A,None,None,None,[par],2,31338,0.000064,0,0,...,ATCTT,A,0.000000e+00,1.179245e-03,0.000000e+00,0.000000e+00,0.000000e+00,6.496037e-05,0.000000e+00,0.000000e+00

In [13]:
df, _ = rs.get_data(standard=False)
df

,consequence,flags,gene_id,gene_symbol,transcript_id,hgvs,hgvsc,hgvsp,lof,lof_filter,lof_flags,pos,rsid,variant_id,exome,genome
0,None,[par],None,None,None,None,None,None,None,None,None,1002741,rs782385877,X-1002741-C-T,None,"{'ac': 1, 'ac_hemi': 0, 'ac_hom': 0, 'an': 313..."
1,None,[par],None,None,None,None,None,None,None,None,None,1002742,rs181914603,X-1002742-G-A,None,"{'ac': 2, 'ac_hemi': 0, 'ac_hom': 0, 'an': 313..."
2,None,[par],None,None,None,None,None,None,None,None,None,1002746,None,X-1002746-TATCA-T,None,"{'ac': 1, 'ac_hemi': 0, 'ac_hom': 0, 'an': 313..."
3,None,[par],None,None,None,None,None,None,None,None,None,1002765,None,X-1002765-TTATC-T,None,"{'ac': 9, 'ac_hemi': 0, 'ac_hom': 0, 'an': 313..."
4,None,[par],None,None,None,None,None,None,None,None,None,1002767,None,X-1002767-ATCTATCTT-A,None,"{'ac': 1, 'ac_hemi': 0, 'ac_hom': 0, 'an': 313..."
5,None,[par],None,None,None,None,None,None,None,None,None,1002771,None,X-1002771-ATCTT-A,None,"{'ac': 2, 'ac_hemi': 0, 'ac_hom': 0, 'an': 313..."

### Transcript Search

In [14]:
from pynoma import TranscriptSearch
ts = TranscriptSearch(3, "ENST00000247933")
df, _ = ts.get_data()
df

,Variant ID,Gene,Consequence,Annotation,Flags,Allele Count,Allele Number,Allele Frequency,Number of Homozygotes,Source,Chromosome,Location,Reference,Alternative
0,4-987010-C-G,IDUA,c.-75C>G,5_prime_UTR_variant,[],1,149172,0.000007,0,Genome,4,987010,C,G
1,4-987013-G-A,IDUA,c.-72G>A,5_prime_UTR_variant,[],3,151256,0.000020,0,Genome,4,987013,G,A
2,4-987014-C-T,IDUA,c.-71C>T,5_prime_UTR_variant,[],37,152092,0.000243,0,Genome,4,987014,C,T
3,4-987021-T-C,IDUA,c.-64T>C,5_prime_UTR_variant,[],2,146758,0.000014,0,Genome,4,987021,T,C
4,4-987023-C-G,IDUA,c.-62C>G,5_prime_UTR_variant,[],1,152126,0.000007,0,Genome,4,987023,C,G
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1199,4-1004450-G-A,IDUA,c.*57G>A,3_prime_UTR_variant,[],1,152196,0.000007,0,Genome,4,1004450,G,A
1200,4-1004450-G-GCA,IDUA,c.*59_*60dup,3_prime_UTR_variant,[],1,152196,0.000007,0,Genome,4,1004450,G,GCA
1201,4-1004452-A-C,IDUA,c.*59A>C,3_prime_UTR_variant,[],7,152152,0.000046,0,Genome,4,1004452,A,C
1202,4-1004458-C-G,IDUA,c.*65C>G,3_prime_UTR_variant,[],2,152180,0.000013,0,Genome,4,1004458,C,G
1203,4-1004459-C-G,IDUA,c.*66C>G,3_prime_UTR_variant,[],23,152202,0.000151,0,Genome,4,1004459,C,G

### Variant Search

In [1]:
from pynoma import VariantSearch
vs = VariantSearch(3, '4-1002747-G-A')
df, meta = vs.get_data()
df

,Allele Count,Allele Number,Number of Homozygotes,Allele Frequency
Other,1,2082,0,0.000480
Other XX,1,1030,0,0.000971
Other XY,0,1052,0,0.000000
Latino,3,15214,0,0.000197
Latino XX,2,6754,0,0.000296
...,...,...,...,...
1KG:CHSXY,0,104,0,0.000000
1KG:GW,0,232,0,0.000000
1KG:GWDXX,0,116,0,0.000000
1KG:GWDXY,0,116,0,0.000000
Total,130,151238,0,0.000860

In [2]:
vs = VariantSearch(2, '4-980866-C-A')
df, meta = vs.get_data()
df

,Allele Count,Allele Number,Number of Homozygotes,Allele Frequency
African,1.0,12584.0,0.0,0.000079
African XX,0.0,5882.0,0.0,0.000000
African XY,1.0,6702.0,0.0,0.000149
Latino,0.0,20714.0,0.0,0.000000
Latino XX,0.0,12188.0,0.0,0.000000
Latino XY,0.0,8526.0,0.0,0.000000
Ashkenazi Jewish,0.0,7168.0,0.0,0.000000
Ashkenazi Jewish XX,0.0,3198.0,0.0,0.000000
Ashkenazi Jewish XY,0.0,3970.0,0.0,0.000000
East Asian,1.0,8262.0,0.0,0.000121
East Asian Japanese,0.0,8.0,0.0,0.000000
East Asian Korean,0.0,1964.0,0.0,0.000000
East Asian Other,1.0,4730.0,0.0,0.000211
East Asian XX,0.0,3970.0,0.0,0.000000
East Asian XY,1.0,4292.0,0.0,0.000233
European (Finnish),0.0,9570.0,0.0,0.000000
European (Finnish) XX,0.0,4822.0,0.0,0.000000
European (Finnish) XY,0.0,4748.0,0.0,0.000000
European (non-Finnish),0.0,69370.0,0.0,0.000000
European (non-Finnish) Bulgarian,0.0,844.0,0.0,0.000000
European (non-Finnish) Estonian,0.0,4652.0,0.0,0.000000
European (non-Finnish) North-western,0.0,26032.0,0.0,0.000000
European (non-Finnish) Other,0.0,17886.0,0.0,0.000000
European (non-Finnish) Southern,0.0,5236.0,0.0,0.000000
European (non-Finnish) Swedish,0.0,14720.0,0.0,0.000000
European (non-Finnish) XX,0.0,28986.0,0.0,0.000000
European (non-Finnish) XY,0.0,40384.0,0.0,0.000000
Other,0.0,3980.0,0.0,0.000000
Other XX,0.0,1916.0,0.0,0.000000
Other XY,0.0,2064.0,0.0,0.000000
South Asian,0.0,19158.0,0.0,0.000000
South Asian XX,0.0,4038.0,0.0,0.000000
South Asian XY,0.0,15120.0,0.0,0.000000
Total XX,0.0,65000.0,0.0,0.000000
Total XY,2.0,85806.0,0.0,0.000023
Total,2.0,150806.0,0.0,0.000013

In [3]:
for row in df.iterrows():
    print(row[0], row[1]['Allele Count'])

African 1.0
African XX 0.0
African XY 1.0
Latino 0.0
Latino XX 0.0
Latino XY 0.0
Ashkenazi Jewish 0.0
Ashkenazi Jewish XX 0.0
Ashkenazi Jewish XY 0.0
East Asian 1.0
East Asian Japanese 0.0
East Asian Korean 0.0
East Asian Other 1.0
East Asian XX 0.0
East Asian XY 1.0
European (Finnish) 0.0
European (Finnish) XX 0.0
European (Finnish) XY 0.0
European (non-Finnish) 0.0
European (non-Finnish) Bulgarian 0.0
European (non-Finnish) Estonian 0.0
European (non-Finnish) North-western 0.0
European (non-Finnish) Other 0.0
European (non-Finnish) Southern 0.0
European (non-Finnish) Swedish 0.0
European (non-Finnish) XX 0.0
European (non-Finnish) XY 0.0
Other 0.0
Other XX 0.0
Other XY 0.0
South Asian 0.0
South Asian XX 0.0
South Asian XY 0.0
Total XX 0.0
Total XY 2.0
Total 2.0

In [4]:
meta

{'variantId': '4-980866-C-A',
 'reference_genome': 'GRCh37',
 'chrom': '4',
 'pos': 980866,
 'ref': 'C',
 'alt': 'A',
 'colocatedVariants': ['4-980866-C-T'],
 'multiNucleotideVariants': None,
 'exome': {'ac': 1,
  'an': 119640,
  'ac_hemi': 0,
  'ac_hom': 0,
  'faf95': {'popmax': None, 'popmax_population': None},
  'filters': [],
  'populations': [{'id': 'AFR',
    'ac': 0,
    'an': 3928,
    'ac_hemi': 0,
    'ac_hom': 0},
   {'id': 'AFR_FEMALE', 'ac': 0, 'an': 2222, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'AFR_MALE', 'ac': 0, 'an': 1706, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'AMR', 'ac': 0, 'an': 19888, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'AMR_FEMALE', 'ac': 0, 'an': 11790, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'AMR_MALE', 'ac': 0, 'an': 8098, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'ASJ', 'ac': 0, 'an': 6878, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'ASJ_FEMALE', 'ac': 0, 'an': 3118, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'ASJ_MALE', 'ac': 0, 'an': 3760, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'EAS', 'ac': 1, 'an': 6702, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'EAS_JPN', 'ac': 0, 'an': 8, 'ac_hemi': None, 'ac_hom': 0},
   {'id': 'EAS_KOR', 'ac': 0, 'an': 1964, 'ac_hemi': None, 'ac_hom': 0},
   {'id': 'EAS_OEA', 'ac': 1, 'an': 4730, 'ac_hemi': None, 'ac_hom': 0},
   {'id': 'EAS_FEMALE', 'ac': 0, 'an': 3432, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'EAS_MALE', 'ac': 1, 'an': 3270, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'FIN', 'ac': 0, 'an': 6184, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'FIN_FEMALE', 'ac': 0, 'an': 3018, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'FIN_MALE', 'ac': 0, 'an': 3166, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'NFE', 'ac': 0, 'an': 54006, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'NFE_BGR', 'ac': 0, 'an': 844, 'ac_hemi': None, 'ac_hom': 0},
   {'id': 'NFE_EST', 'ac': 0, 'an': 82, 'ac_hemi': None, 'ac_hom': 0},
   {'id': 'NFE_NWE', 'ac': 0, 'an': 17468, 'ac_hemi': None, 'ac_hom': 0},
   {'id': 'NFE_ONF', 'ac': 0, 'an': 15760, 'ac_hemi': None, 'ac_hom': 0},
   {'id': 'NFE_SEU', 'ac': 0, 'an': 5132, 'ac_hemi': None, 'ac_hom': 0},
   {'id': 'NFE_SWE', 'ac': 0, 'an': 14720, 'ac_hemi': None, 'ac_hom': 0},
   {'id': 'NFE_FEMALE', 'ac': 0, 'an': 22216, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'NFE_MALE', 'ac': 0, 'an': 31790, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'OTH', 'ac': 0, 'an': 2896, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'OTH_FEMALE', 'ac': 0, 'an': 1356, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'OTH_MALE', 'ac': 0, 'an': 1540, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'SAS', 'ac': 0, 'an': 19158, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'SAS_FEMALE', 'ac': 0, 'an': 4038, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'SAS_MALE', 'ac': 0, 'an': 15120, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'FEMALE', 'ac': 0, 'an': 51190, 'ac_hemi': 0, 'ac_hom': 0},
   {'id': 'MALE', 'ac': 1, 'an': 68450, 'ac_hemi': 0, 'ac_hom': 0}],
  'age_distribution': {'het': {'bin_edges': [30,
     35,
     40,
     45,
     50,
     55,
     60,
     65,
     70,
     75,
     80],
    'bin_freq': [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    'n_smaller': 0,
    'n_larger': 0},
   'hom': {'bin_edges': [30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80],
    'bin_freq': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'n_smaller': 0,
    'n_larger': 0}},
  'qualityMetrics': {'alleleBalance': {'alt': {'bin_edges': [0,
      0.05,
      0.1,
      0.15,
      0.2,
      0.25,
      0.3,
      0.35,
      0.4,
      0.45,
      0.5,
      0.55,
      0.6,
      0.65,
      0.7,
      0.75,
      0.8,
      0.85,
      0.9,
      0.95,
      1],
     'bin_freq': [0, 0, 10, 8, 2, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     'n_smaller': 0,
     'n_larger': 0}},
   'genotypeDepth': {'all': {'bin_edges': [0,
      5,
      10,
      15,
      20,
      25,
      30,
      35,
      40,
      45,
      50,
      55,
      60,
      65,
      70,
      75,
      80,
      85,
      90,
      95,
      100],
     'bin_freq': [38361,
      26585,
      19442,
      13011,
      10226,
      6187,
      5130,
      5323,
      1212,
      181,
      56,
      15,
      8,
      3,
      2,
      2,
      0,
      1,
      0,
      0],
     'n_smaller': 0,
     'n_larger': 3},
    'alt': {'bin_edges': [0,
      5,
      10,
      15,
      20,
      25,
      30,
      35,
      40,
      45,
      50,
      55,
      60,
      65,
      70,
      75,
      80,
      85,
      90,
      95,
      100],
     'bin_freq': [0, 7, 13, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     'n_smaller': 0,
     'n_larger': 0}},
   'genotypeQuality': {'all': {'bin_edges': [0,
      5,
      10,
      15,
      20,
      25,
      30,
      35,
      40,
      45,
      50,
      55,
      60,
      65,
      70,
      75,
      80,
      85,
      90,
      95,
      100],
     'bin_freq': [7056,
      14233,
      7006,
      12882,
      11150,
      5108,
      8633,
      7071,
      3051,
      5261,
      4507,
      2024,
      5289,
      1493,
      2402,
      1479,
      2560,
      472,
      1949,
      6097],
     'n_smaller': 0,
     'n_larger': 0},
    'alt': {'bin_edges': [0,
      5,
      10,
      15,
      20,
      25,
      30,
      35,
      40,
      45,
      50,
      55,
      60,
      65,
      70,
      75,
      80,
      85,
      90,
      95,
      100],
     'bin_freq': [6, 4, 4, 3, 1, 4, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0],
     'n_smaller': 0,
     'n_larger': 0}},
   'siteQualityMetrics': [{'metric': 'BaseQRankSum', 'value': -1.067},
    {'metric': 'ClippingRankSum', 'value': -0.067},
    {'metric': 'DP', 'value': 2224721},
    {'metric': 'FS', 'value': 4.571},
    {'metric': 'InbreedingCoeff', 'value': 0.0261},
    {'metric': 'MQ', 'value': 60},
    {'metric': 'MQRankSum', 'value': 0.11},
    {'metric': 'pab_max', 'value': 1},
    {'metric': 'QD', 'value': 0.78},
    {'metric': 'ReadPosRankSum', 'value': 0.572},
    {'metric': 'RF', 'value': 0.20822502302944865},
    {'metric': 'SiteQuality', 'value': 703.21},
    {'metric': 'SOR', 'value': 0.374},
    {'metric': 'VQSLOD', 'value': -2.103},
    {'metric': 'VQSR_NEGATIVE_TRAIN_SITE', 'value': 1},
    {'metric': 'VQSR_POSITIVE_TRAIN_SITE', 'value': None}]}},
 'genome': {'ac': 1,
  'an': 31166,
  'ac_hemi': 0,
  'ac_hom': 0,
  'faf95': {'popmax': None, 'popmax_population': None},
  'filters': [],
  'age_distribution': {'het': {'bin_edges': [30,
     35,
     40,
     45,
     50,
     55,
     60,
     65,
     70,
     75,
     80],
    'bin_freq': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'n_smaller': 0,
    'n_larger': 0},
   'hom': {'bin_edges': [30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80],
    'bin_freq': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'n_smaller': 0,
    'n_larger': 0}},
  'qualityMetrics': {'alleleBalance': {'alt': {'bin_edges': [0,
      0.05,
      0.1,
      0.15,
      0.2,
      0.25,
      0.3,
      0.35,
      0.4,
      0.45,
      0.5,
      0.55,
      0.6,
      0.65,
      0.7,
      0.75,
      0.8,
      0.85,
      0.9,
      0.95,
      1],
     'bin_freq': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     'n_smaller': 0,
     'n_larger': 0}},
   'genotypeDepth': {'all': {'bin_edges': [0,
      5,
      10,
      15,
      20,
      25,
      30,
      35,
      40,
      45,
      50,
      55,
      60,
      65,
      70,
      75,
      80,
      85,
      90,
      95,
      100],
     'bin_freq': [15,
      96,
      366,
      1222,
      2927,
      3175,
      4014,
      3023,
      675,
      129,
      35,
      15,
      6,
      3,
      2,
      1,
      2,
      1,
      1,
      0],
     'n_smaller': 0,
     'n_larger': 0},
    'alt': {'bin_edges': [0,
      5,
      10,
      15,
      20,
      25,
      30,
      35,
      40,
      45,
      50,
      55,
      60,
      65,
      70,
      75,
      80,
      85,
      90,
      95,
      100],
     'bin_freq': [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     'n_smaller': 0,
     'n_larger': 0}},
   'genotypeQuality': {'all': {'bin_edges': [0,
      5,
      10,
      15,
      20,
      25,
      30,
      35,
      40,
      45,
      50,
      55,
      60,
      65,
      70,
      75,
      80,
      85,
      90,
      95,
      100],
     'bin_freq': [5,
      15,
      14,
      26,
      54,
      51,
      129,
      208,
      182,
      426,
      645,
      415,
      1611,
      547,
      1292,
      724,
      1856,
      367,
      1720,
      5421],
     'n_smaller': 0,
     'n_larger': 0},
    'alt': {'bin_edges': [0,
      5,
      10,
      15,
      20,
      25,
      30,
      35,
      40,
      45,
      50,
      55,
      60,
      65,
      70,
      75,
      80,
      85,
      90,
      95,
      100],
     'bin_freq': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     'n_smaller': 0,
     'n_larger': 0}},
   'siteQualityMetrics': [{'metric': 'BaseQRankSum', 'value': 1.43},
    {'metric': 'ClippingRankSum', 'value': -0.835},
    {'metric': 'DP', 'value': 608180},
    {'metric': 'FS', 'value': 4.1},
    {'metric': 'InbreedingCoeff', 'value': 0.0017},
    {'metric': 'MQ', 'value': 60},
    {'metric': 'MQRankSum', 'value': 1.55},
    {'metric': 'pab_max', 'value': 0.3074562549591067},
    {'metric': 'QD', 'value': 20.94},
    {'metric': 'ReadPosRankSum', 'value': -1.61},
    {'metric': 'RF', 'value': 0.6972491779403581},
    {'metric': 'SiteQuality', 'value': 502.48},
    {'metric': 'SOR', 'value': 0.164},
    {'metric': 'VQSLOD', 'value': 11.29},
    {'metric': 'VQSR_NEGATIVE_TRAIN_SITE', 'value': None},
    {'metric': 'VQSR_POSITIVE_TRAIN_SITE', 'value': None}]}},
 'flags': [],
 'rsid': 'rs990934606',
 'sortedTranscriptConsequences': [{'canonical': True,
   'gene_id': 'ENSG00000127415',
   'gene_version': '8',
   'gene_symbol': 'IDUA',
   'hgvs': 'c.-7C>A',
   'hgvsc': 'c.-7C>A',
   'hgvsp': None,
   'lof': None,
   'lof_flags': None,
   'lof_filter': None,
   'major_consequence': '5_prime_UTR_variant',
   'polyphen_prediction': None,
   'sift_prediction': None,
   'transcript_id': 'ENST00000247933',
   'transcript_version': '4'},
  {'canonical': None,
   'gene_id': 'ENSG00000127415',
   'gene_version': '8',
   'gene_symbol': 'IDUA',
   'hgvs': 'c.-7C>A',
   'hgvsc': 'c.-7C>A',
   'hgvsp': None,
   'lof': None,
   'lof_flags': None,
   'lof_filter': None,
   'major_consequence': '5_prime_UTR_variant',
   'polyphen_prediction': None,
   'sift_prediction': None,
   'transcript_id': 'ENST00000453894',
   'transcript_version': '1'},
  {'canonical': None,
   'gene_id': 'ENSG00000127415',
   'gene_version': '8',
   'gene_symbol': 'IDUA',
   'hgvs': 'c.-7C>A',
   'hgvsc': 'c.-7C>A',
   'hgvsp': None,
   'lof': None,
   'lof_flags': None,
   'lof_filter': None,
   'major_consequence': '5_prime_UTR_variant',
   'polyphen_prediction': None,
   'sift_prediction': None,
   'transcript_id': 'ENST00000502910',
   'transcript_version': '1'},
  {'canonical': None,
   'gene_id': 'ENSG00000145217',
   'gene_version': '9',
   'gene_symbol': 'SLC26A1',
   'hgvs': 'c.576+4050G>T',
   'hgvsc': 'c.576+4050G>T',
   'hgvsp': None,
   'lof': None,
   'lof_flags': None,
   'lof_filter': None,
   'major_consequence': 'intron_variant',
   'polyphen_prediction': None,
   'sift_prediction': None,
   'transcript_id': 'ENST00000398520',
   'transcript_version': '2'},
  {'canonical': None,
   'gene_id': 'ENSG00000127415',
   'gene_version': '8',
   'gene_symbol': 'IDUA',
   'hgvs': 'n.3C>A',
   'hgvsc': 'n.3C>A',
   'hgvsp': None,
   'lof': None,
   'lof_flags': None,
   'lof_filter': None,
   'major_consequence': 'non_coding_transcript_exon_variant',
   'polyphen_prediction': None,
   'sift_prediction': None,
   'transcript_id': 'ENST00000506561',
   'transcript_version': '1'},
  {'canonical': None,
   'gene_id': 'ENSG00000127415',
   'gene_version': '8',
   'gene_symbol': 'IDUA',
   'hgvs': 'n.13C>A',
   'hgvsc': 'n.13C>A',
   'hgvsp': None,
   'lof': None,
   'lof_flags': None,
   'lof_filter': None,
   'major_consequence': 'non_coding_transcript_exon_variant',
   'polyphen_prediction': None,
   'sift_prediction': None,
   'transcript_id': 'ENST00000508168',
   'transcript_version': '1'},
  {'canonical': None,
   'gene_id': 'ENSG00000127415',
   'gene_version': '8',
   'gene_symbol': 'IDUA',
   'hgvs': 'n.35C>A',
   'hgvsc': 'n.35C>A',
   'hgvsp': None,
   'lof': None,
   'lof_flags': None,
   'lof_filter': None,
   'major_consequence': 'non_coding_transcript_exon_variant',
   'polyphen_prediction': None,
   'sift_prediction': None,
   'transcript_id': 'ENST00000514698',
   'transcript_version': '1'}]}

In [5]:
vs = VariantSearch(2, '4-980801-G-A')
df, meta = vs.get_data()
df

,Allele Count,Allele Number,Number of Homozygotes,Allele Frequency
African,0.0,8642.0,0.0,0.000000
African XX,0.0,3654.0,0.0,0.000000
African XY,0.0,4988.0,0.0,0.000000
Latino,0.0,842.0,0.0,0.000000
Latino XX,0.0,410.0,0.0,0.000000
Latino XY,0.0,432.0,0.0,0.000000
Ashkenazi Jewish,0.0,286.0,0.0,0.000000
Ashkenazi Jewish XX,0.0,78.0,0.0,0.000000
Ashkenazi Jewish XY,0.0,208.0,0.0,0.000000
East Asian,0.0,1558.0,0.0,0.000000
East Asian Japanese,0.0,0.0,0.0,0.000000
East Asian Korean,0.0,0.0,0.0,0.000000
East Asian Other,0.0,0.0,0.0,0.000000
East Asian XX,0.0,538.0,0.0,0.000000
East Asian XY,0.0,1020.0,0.0,0.000000
European (Finnish),0.0,3446.0,0.0,0.000000
European (Finnish) XX,0.0,1838.0,0.0,0.000000
European (Finnish) XY,0.0,1608.0,0.0,0.000000
European (non-Finnish),2.0,15334.0,0.0,0.000130
European (non-Finnish) Bulgarian,0.0,0.0,0.0,0.000000
European (non-Finnish) Estonian,0.0,4524.0,0.0,0.000000
European (non-Finnish) North-western,2.0,8572.0,0.0,0.000233
European (non-Finnish) Other,0.0,2134.0,0.0,0.000000
European (non-Finnish) Southern,0.0,104.0,0.0,0.000000
European (non-Finnish) Swedish,0.0,0.0,0.0,0.000000
European (non-Finnish) XX,2.0,6762.0,0.0,0.000296
European (non-Finnish) XY,0.0,8572.0,0.0,0.000000
Other,0.0,1086.0,0.0,0.000000
Other XX,0.0,562.0,0.0,0.000000
Other XY,0.0,524.0,0.0,0.000000
South Asian,0.0,0.0,0.0,0.000000
South Asian XX,0.0,0.0,0.0,0.000000
South Asian XY,0.0,0.0,0.0,0.000000
Total XX,2.0,13842.0,0.0,0.000144
Total XY,0.0,17352.0,0.0,0.000000
Total,2.0,31194.0,0.0,0.000064